FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN yarn install

RUN yar db:generate
# Can you add a script to the global package.json that does this?
RUN cd packages/db && yarn prisma generate && cd ../..

# Can you filter the build down to just one app?
RUN yarn build

CMD ["npm", "run", "start-user-app"]